#角斗场所在的世界
world: world
#角斗场世界的统一重生点
spawn: 124,96,24
#角斗场是否可以建筑
build: true
#是否启用粒子效果(连续击杀5人的奖励)
effect: true
#标准装备配置
standardkit:
  #0为空 1为皮革 2为铁 3为钻石
  armor:
    a: 2
    b: 0
    c: 1
    d: 0
  #0为空 1为木剑 2为石剑 3为铁剑 4为钻石剑
  sword: 2